### ISSUE TITLE
sqlite3.OperationalError: no such table: texts

### ISSUE THREAD

**Issue by ihammad90** [mitchelldehaven/bevers#2]
While running bash run_fever.sh i am getting sqlite3.OperationalError: no such table: texts.

**Comment by mitchelldehaven** [comment]
Okay, I'll take a look.

**Comment by mitchelldehaven** [comment]
Sorry about the delay. Ended up being out of town for a week. I think I found what the problem likely was. I was able to re-run and didn't run into the problem your describing. What likely happened is one of the downloads failed and the bash script doesn't have `set -euo pipefail` in it, so if a command fails it just continues to run the remaining commands without the correct files. `python src/data/convert_db.py` is where the `texts` table is created. Try running again with either the latest commit or manually add `set -eou pipefail` to the top of the bash script.
