### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by ihammad90** [mitchelldehaven/bevers#3]
Now with the new repo you shared , while running the bash run_fever.sh command

i encountered this issue

Traceback (most recent call last):
  File "src/data/tfidf.py", line 15, in <module>
    from sklearn.feature_extraction.text import TfidfVectorizer
  File "/home/azureuser/anaconda3/envs/bevers/lib/python3.8/site-packages/sklearn/feature_extraction/__init__.py", line 9, in <module>
    from .image import img_to_graph, grid_to_graph
  File "/home/azureuser/anaconda3/envs/bevers/lib/python3.8/site-packages/sklearn/feature_extraction/image.py", line 167, in <module>
    dtype=np.int):
  File "/home/azureuser/anaconda3/envs/bevers/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

Note: all requirements were used which you shared in requirements.txt and setup.sh file.

**Comment by mitchelldehaven** [comment]
Sorry, something must have changed with a requirement somewhere, as the problem is that `numpy<1.24` is required, but the current `setup.sh` script installs `1.24.3`.

I added `numpy==1.23.5` to the requirements. If you want to avoid rebuilding the conda environment, then you can probably just run `pip install numpy==1.23.5`.
