### ISSUE TITLE
Attaching a License

### ISSUE THREAD

**Issue by LightenedLimited** [mitchelldehaven/bevers#5]
Hi!

I read your paper on BEVERS, and I thought it super interesting how a tried-and-tested approach is so much more performant than other solutions. 

I'd love to use some of the code on GitHub for further work on other tasks, but I noticed there isn't a license for the code attached to the BEVERS repo. Is it possible to attach a license like the MIT license or create/distribute derivative work?

**Comment by mitchelldehaven** [comment]
Sure, just added an MIT license.
